### ISSUE TITLE
Not allowed to add devices from valid account

### ISSUE THREAD

**Issue by fredzannarbor** [stephanie-wang/kindlebox#10]
![screenshot from 2016-07-26 15-31-23](https://cloud.githubusercontent.com/assets/1165771/17152515/12409410-5346-11e6-9b3c-a1a14789726a.png)

These devices are registered with my Amazon account. It's possible I'm double signed up with GetBookDrop for this account wfzimmerman at gmail dort com, can you check?

**Comment by stephanie-wang** [comment]
Hmm, that's strange. Have you tried this again recently, with a fresh copy of the bookmarklet? If it's still not working, can you do me a favor and download this webpage as an HTML file and send it to me at wang.stephanie93@gmail.com? Thanks!

**Comment by fredzannarbor** [comment]
I deregistered the device, reregistered, logged out/in to Dropbox & Amazon,
& it worked. thanks ! Great app.  need any help on the open source?

Open source:
https://github.com/fredzannarbor/pagekicker-community/wiki
iOS : https://itunes.apple.com/us/app/pagekicker/id1079882706?ls=1&mt=8
Android:
https://play.google.com/store/apps/details?id=com.pagekicker.www&hl=en
Enterprise: https://www.PageKicker.com

**Comment by stephanie-wang** [comment]
Great! Yeah, I'd like to get this into shape so that others can actually extend it themselves, but haven't had time yet. Let me know if you want to try it yourself!
