### ISSUE TITLE
Unable to run Kindlebox

### ISSUE THREAD

**Issue by zeshan-ae** [stephanie-wang/kindlebox#12]
Hi,

I am trying to run Kindlebox but am facing two issues:

1. When the shared folder on Dropbox is opened, it says there was some problem, but no details are shared.

2. On following the steps defined at: https://getbookdrop.com/#/home/devices/1  
I am unable to see the button "Activate Kindlebox". I have shared a snapshot of my Amazon account on the following link:

https://cloud.githubusercontent.com/assets/25391011/22380971/69333a84-e4e1-11e6-9a6d-8119a7f6b111.png

Note: I do not use the paid Amazon services. Could this be the reason of my limited user experience?

Question: Is it possible to sync between my Kindle Android App and Kindle device using Kindlebox?

Thanks,
Zeshan

**Comment by stephanie-wang** [comment]
Sorry for the delayed response! Perhaps try the activation process again? For the second issue, the "Activate Kindlebox" button is actually a bookmarklet. On the Bookdrop website, you should click and drag the button to your bookmarks bar. Then, click the bookmarklet once you're on the Amazon site.
