### ISSUE TITLE
Dropbox disabled Bookdrop

### ISSUE THREAD

**Issue by marshmallowcreme** [stephanie-wang/kindlebox#13]
When I try to login to Dropbox, it says this app is disabled. So we need the new "local" version that's promised on the readme!

**Comment by yanowitz** [comment]
@stephanie-wang I don't see the app disabled, but it looks like the domain expired? What's the status of the project? Can we help with either setting up a local version or can you post instructions for your heroku configuration? Love/miss this app already! Thanks.

**Comment by brgale** [comment]
I'm having the same issue - dropbox says the app is disabled.  I would love a fix.

**Comment by stephanie-wang** [comment]
So sorry, but my Dropbox account was recently disabled, so the app is temporarily unavailable. I'll try to get it up and running again this weekend. Please bear with me!

**Comment by qianmj** [comment]
I'm having the same "app is disabled" error, is there any updates on this issue? Thanks

**Comment by groverlynn** [comment]
same issue here

**Comment by jetwitaussi** [comment]
Hello, Any update? This service is very useful, would be nice to get it back ;) Thanks a lot!

**Comment by marshmallowcreme** [comment]
@stephanie-wang our brains are atrophying from disuse. please save us!

**Comment by stephanie-wang** [comment]
I'm so sorry! I've been very busy with work recently, but I will hopefully have time this weekend or next to get this sorted out! Stay tuned. :)

**Comment by jetwitaussi** [comment]
Any update? :)

**Comment by supermelodrama** [comment]
I contributed to this project and am willing to contribute again if might help get it resolved? I'll pledge $50. Any others willing to pony up?

**Comment by Oldenborg** [comment]
I will throw in a few $.. its starting to annoy me that I have to move everything to my kindle manually.. Think about it.. The people complaining here are mostly developers.. what about all the regular people using this?

I will start working on an alternative if something doesn't happen soon.

**Comment by jer2665** [comment]
I'm hoping for an update at some point, but couldn't wait any longer. So for now I just made an IFTTT applet to run it for me. Might be an easy fix for people while we wait. I just did IF dropbox THEN gmail to send it to my kindle email.

**Comment by stephanie-wang** [comment]
I'm so sorry, I've been pretty busy, but I finally got around to this! You can all reactivate your accounts at [getbookdrop.com](getbookdrop.com)! I had to install a new Dropbox app, so **after logging in with Dropbox, make sure to move your books to the new folder Dropbox/my-bookdrop**.

Thanks for being patient with me! The service should be more available starting now. Please let me know if you're still having issues. :)

**Comment by MoAl78741** [comment]
Getting the error..
This app is unable to link additional users because it has been frozen pending review.

**Comment by RobotechMaster** [comment]
Getting the same "unable to link additional users" error, and it's been several months...

**Comment by Oldenborg** [comment]
I dot think this app is being maintained anymore

**Comment by jetwitaussi** [comment]
Stuck on error 500 when returning to the site after dropbox authentication :(

**Comment by jetwitaussi** [comment]
still the problem... any solution ???
