### ISSUE TITLE
Books won't sync with my Amazon Account

### ISSUE THREAD

**Issue by dustdingo** [stephanie-wang/kindlebox#3]
I've gone ahead and authorized the app via the website numerous times, I go to the devices page and pick my Paperwhite as the Kindle to receive my books, but it hasn't been sending over books. I've removed my books, added them again, and even added new books.

Looking at my Dropbox account, I have a dual account setup - both a personal dropbox as well as a business one. They're linked together, but everything is set up to sync with my personal dropbox. The folder is in the Apps folder, but nothing has e-mailed over to show up in my Amazon account.

I've also been trying to get it working for a few days, so I don't believe it's a matter of waiting.

Any idea what I may be doing wrong?  Thanks for developing this - I look forward to using this! It seems like a great setup!

**Comment by stephanie-wang** [comment]
Hey, so I think this is probably an issue with my server setup a couple days ago, and not the code here on github (and definitely not Dropbox!). I've been handling some users who are having this problem individually, so can you email me at swang93@mit.edu with your user ID (you can find it at kindlebox.me/error). Thanks!
