### ISSUE TITLE
Bookdrop is not creating shared folder.

### ISSUE THREAD

**Issue by gbrennon** [stephanie-wang/kindlebox#5]
I've signed up with my dropbox account and Bookdrop did not create a folder on my dropbox account. I've created 1 for myself but it doesn''t send Kindle my updates

**Comment by gbrennon** [comment]
I've found the way to. Bookdrop did not create a folder on my dropbox and it isn't using my dropbox folder, but added the "welcome to bookdrop" pdf to my amazon cloud drive.

How can I sync it with my dropbox?

**Comment by gbrennon** [comment]
Sorry, as my dropbox is in portuguese the "Apps" folder was created under the name "Aplicativos" and I thought the pattern would be Apps/book-drop.

Found the folder. Sorry for the wrong issue

**Comment by stephanie-wang** [comment]
No problem! Glad you figured it out okay.
