### ISSUE TITLE
Do PDFs get converted automatically?

### ISSUE THREAD

**Issue by karthikraman** [stephanie-wang/kindlebox#7]
Can I disable conversion of PDFs? I just want the PDFs to show up in my Kindle, without conversion...

**Comment by stephanie-wang** [comment]
Hi,

Unfortunately, this part is up to Amazon. They require every file on your Kindle to be in Kindle format (.mobi), so they will convert PDFs automatically. Thanks!

Stephanie

**Comment by karthikraman** [comment]
Thanks, it's a wonderful product anyways!
